# Queue Runners

In [2]:
import tensorflow as tf 

## Import csv files
<hr/>
### first 
```python

filename_queue = tf.train.string_input_producer(['data-01-test-score.csv', 
                                                'data-02-stock_daily.csv', 
                                                'data-03-diabetes.csv'],
                                                shuffle=False, name='filename_queue')
```

### second

```python
reader = tf.TextLineReader()
key, value = reader.read(filename_queue)
```
### third
```python
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)
```
<hr/>

## tf.train.batch
<hr/>

### collect batches of csv in 
```python
train_x_batch, train_y_batch = \
    tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

sess = tf.Session()
...
```
### start populating the filename queue
```python
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess2, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    ...
    
coord.request_stop()
coord.join(threads)
```

<hr/>
## example

In [3]:
filename_queue = tf.train.string_input_producer(['data-01-test-score.csv'],
                                               shuffle=False,
                                               name='filename_queue')

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)


record_defaults = [[0.],[0.],[0.],[0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

train_x_batch, train_y_batch = \
    tf.train.batch([xy[0:-1],xy[-1:]], batch_size=10)


    
X = tf.placeholder("float32", shape = [None, 3])
Y = tf.placeholder("float32", shape = [None, 1])
W = tf.Variable(tf.random_normal([3,1]), name='Weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X,W) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))

sess = tf.Session()
sess.run(tf.global_variables_initializer())

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict={X:x_batch, Y:y_batch})
    
    if step % 20 == 0:
        print(step, "cost: ", cost_val,
             "\nPrediction::\n",hy_val)
        
coord.request_stop()
coord.join(threads)

0 cost:  11218.399 
Prediction::
 [[281.5941 ]
 [298.45087]
 [314.9737 ]
 [340.4989 ]
 [219.57545]
 [152.93675]
 [262.05515]
 [205.57835]
 [266.3614 ]
 [237.29561]]
20 cost:  433.15787 
Prediction::
 [[173.43303 ]
 [168.72676 ]
 [187.00894 ]
 [201.17828 ]
 [120.672874]
 [ 80.11798 ]
 [157.75494 ]
 [128.229   ]
 [145.24107 ]
 [125.2277  ]]
40 cost:  426.72226 
Prediction::
 [[173.27524]
 [168.83122]
 [186.95653]
 [201.16766]
 [120.78727]
 [ 80.3084 ]
 [157.73358]
 [128.1857 ]
 [145.46371]
 [125.56294]]
60 cost:  420.31903 
Prediction::
 [[173.12364]
 [168.94077]
 [186.91032]
 [201.16338]
 [120.90539]
 [ 80.50054]
 [157.7169 ]
 [128.14584]
 [145.68999]
 [125.90032]]
80 cost:  414.01776 
Prediction::
 [[172.97327]
 [169.04955]
 [186.86458]
 [201.1591 ]
 [121.0227 ]
 [ 80.69109]
 [157.70013]
 [128.10591]
 [145.91441]
 [126.23472]]
100 cost:  407.81674 
Prediction::
 [[172.82408 ]
 [169.15749 ]
 [186.81921 ]
 [201.15477 ]
 [121.13923 ]
 [ 80.88008 ]
 [157.68327 ]
 [128.06589 ]
 [146.13698 ]

960 cost:  216.22331 
Prediction::
 [[167.43083]
 [173.12721]
 [185.21736]
 [200.96216]
 [125.48378]
 [ 87.69745]
 [156.91225]
 [126.30914]
 [154.16667]
 [138.36713]]
980 cost:  213.13171 
Prediction::
 [[167.32631 ]
 [173.20564 ]
 [185.18715 ]
 [200.95763 ]
 [125.57091 ]
 [ 87.829216]
 [156.89368 ]
 [126.268166]
 [154.32188 ]
 [138.59175 ]]
1000 cost:  210.0878 
Prediction::
 [[167.22261]
 [173.2835 ]
 [185.15723]
 [200.95308]
 [125.65749]
 [ 87.95994]
 [156.8751 ]
 [126.22721]
 [154.47585]
 [138.8144 ]]
1020 cost:  207.09102 
Prediction::
 [[167.11977 ]
 [173.3608  ]
 [185.1276  ]
 [200.94853 ]
 [125.7435  ]
 [ 88.08958 ]
 [156.8565  ]
 [126.186295]
 [154.62857 ]
 [139.03511 ]]
1040 cost:  204.14037 
Prediction::
 [[167.01775 ]
 [173.43756 ]
 [185.09824 ]
 [200.94398 ]
 [125.828964]
 [ 88.218185]
 [156.83792 ]
 [126.14539 ]
 [154.78008 ]
 [139.25388 ]]
1060 cost:  201.23543 
Prediction::
 [[166.91652]
 [173.51376]
 [185.06912]
 [200.93945]
 [125.91383]
 [ 88.34574]
 [156.81932]
 [126

1920 cost:  110.55168 
Prediction::
 [[163.2444  ]
 [176.3282  ]
 [184.04164 ]
 [200.74712 ]
 [129.09187 ]
 [ 92.961685]
 [156.02351 ]
 [124.38981 ]
 [160.3686  ]
 [147.20119 ]]
1940 cost:  109.06881 
Prediction::
 [[163.17297]
 [176.3841 ]
 [184.02228]
 [200.74277]
 [129.1559 ]
 [ 93.05125]
 [156.00536]
 [124.35129]
 [160.47412]
 [147.34857]]
1960 cost:  107.60826 
Prediction::
 [[163.10207 ]
 [176.43956 ]
 [184.0031  ]
 [200.73842 ]
 [129.2195  ]
 [ 93.140076]
 [155.98718 ]
 [124.31284 ]
 [160.57878 ]
 [147.49463 ]]
1980 cost:  106.16931 
Prediction::
 [[163.03174 ]
 [176.49466 ]
 [183.9841  ]
 [200.73409 ]
 [129.28271 ]
 [ 93.2282  ]
 [155.96906 ]
 [124.274475]
 [160.68265 ]
 [147.63943 ]]
2000 cost:  104.75185 
Prediction::
 [[162.96198]
 [176.54936]
 [183.96526]
 [200.72975]
 [129.34554]
 [ 93.31563]
 [155.95094]
 [124.23615]
 [160.78564]
 [147.78299]]
