# Lecture 4
## - Multivariable linear regression

### Hypothesis 
- if there is one x

    - \\(H(x) = Wx + b\\)

- if there are more x 

    - \\(H(x_1,x_2,x_3) = W_1x_1 + W_2x_2 + W_3x_3 + b\\)
    
### Cost function

- \\( cost(W,b) = \frac{1}{m}\sum_{i=1}^{m} (H(x_1^i, x_2^i, x_3^i) - y^i)^2 \\)

<hr/>
## - Matrix
### Hypothesis using matrix
- \\((x_1,x_2,x_3) * \left( \begin{array}{c}W_{1}\\W_{2}\\W_{3}\\\end{array}\right) = (x_1W_1 + x_2W_2 + x_3W_3)\\)

- if there are a lot instance

    - \\(\left( \begin{array}{c}x_{11} x_{12} x_{13}\\x_{21} x_{22} x_{23}\\x_{31} x_{32} x_{33}\\x_{41} x_{42} x_{43}\\x_{51} x_{52} x_{53}\\\end{array}\right) * \left( \begin{array}{c}W_{1}\\W_{2}\\W_{3}\\\end{array}\right) = \left( \begin{array}{c}
x_{11}W_1 + x_{12}W_2 + x_{13}W_3\\x_{21}W_1+ x_{22}W_2+ x_{23}W_3\\x_{31}W_1+ x_{32}W_2+ x_{33}W_3\\x_{41}W_1+ x_{42}W_2+ x_{43}W_3\\x_{51}W_1+ x_{52}W_2+ x_{53}W_3\\\end{array}\right)\\)

    - [5,3] * [3,1] = [5,1]
    
    
- \\(H(X) = XW\\)


### example
| x_1    	|   x_2 	|   x_3 	|   Y   	|
|:--------:	|----------	|:--------:	|----------	|
| 73       	| 80       	| 75       	| 152       |
| 93       	| 88       	| 93       	| 185       |
| 89       	| 91       	|90        	| 180      	|
| 96       	| 98       	|100       	| 196      	|
| 73       	| 66       	|70       	| 142      	|

In [2]:
import tensorflow as tf

/Users/che/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [3]:
# without Matrix

x1_data = [73.,93.,89.,96.,73.]
x2_data = [80.,88.,91.,98.,66.]
x3_data = [75.,93.,90.,100.,70.]
y_data = [152.,185.,180.,196.,142.]

x1 = tf.placeholder("float32")
x2 = tf.placeholder("float32")
x3 = tf.placeholder("float32")
Y = tf.placeholder("float32")

w1 = tf.Variable(tf.random_normal([1]), name = 'weight1')
w2 = tf.Variable(tf.random_normal([1]), name = 'weight1')
w3 = tf.Variable(tf.random_normal([1]), name = 'weight1')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict = {x1:x1_data, x2:x2_data, x3:x3_data, Y:y_data})
    if step % 10 == 0:
        print(step, "Cost: ",cost_val,"\nprediction:\n",hy_val,"\n")
        


0 Cost:  60679.5 
prediction:
 [-66.90109  -78.118996 -77.80018  -86.36754  -58.139526] 

10 Cost:  0.89023936 
prediction:
 [151.00772 183.79115 180.26434 194.65842 141.63184] 

20 Cost:  0.3347209 
prediction:
 [151.66704 184.58357 181.04512 195.50879 142.23615] 

30 Cost:  0.33467233 
prediction:
 [151.66902 184.58598 181.04749 195.51152 142.23784] 

40 Cost:  0.33463302 
prediction:
 [151.66902 184.58597 181.04747 195.51164 142.23772] 

50 Cost:  0.3345868 
prediction:
 [151.669   184.58597 181.04744 195.51176 142.2376 ] 

60 Cost:  0.3345451 
prediction:
 [151.66899 184.58595 181.04742 195.5119  142.23746] 

70 Cost:  0.3345077 
prediction:
 [151.66899 184.58595 181.04741 195.51201 142.23735] 

80 Cost:  0.33445412 
prediction:
 [151.66898 184.58595 181.04738 195.51216 142.23721] 

90 Cost:  0.3344153 
prediction:
 [151.66898 184.58595 181.04736 195.51227 142.23709] 

100 Cost:  0.3343687 
prediction:
 [151.66896 184.58594 181.04733 195.5124  142.23697] 

110 Cost:  0.33432665 
pr

980 Cost:  0.3307022 
prediction:
 [151.66756 184.58566 181.0453  195.52312 142.22636] 

990 Cost:  0.33065075 
prediction:
 [151.66754 184.58566 181.04526 195.52324 142.22624] 

1000 Cost:  0.330618 
prediction:
 [151.66751 184.58565 181.04524 195.52336 142.22614] 

1010 Cost:  0.33057934 
prediction:
 [151.6675  184.58565 181.04523 195.52348 142.22601] 

1020 Cost:  0.33053318 
prediction:
 [151.66748 184.58566 181.0452  195.5236  142.2259 ] 

1030 Cost:  0.33050048 
prediction:
 [151.66745 184.58565 181.04518 195.52373 142.2258 ] 

1040 Cost:  0.33045793 
prediction:
 [151.66743 184.58566 181.04517 195.52385 142.22566] 

1050 Cost:  0.33041772 
prediction:
 [151.66743 184.58565 181.04514 195.52396 142.22556] 

1060 Cost:  0.33037323 
prediction:
 [151.6674  184.58565 181.0451  195.5241  142.22545] 

1070 Cost:  0.3303399 
prediction:
 [151.66739 184.58566 181.0451  195.52422 142.22534] 

1080 Cost:  0.3302892 
prediction:
 [151.66736 184.58566 181.04506 195.52434 142.2252 ] 

1090 C

1970 Cost:  0.3267828 
prediction:
 [151.66508 184.586   181.04277 195.5347  142.21558] 

1980 Cost:  0.32674396 
prediction:
 [151.66504 184.58601 181.04276 195.53484 142.21545] 

1990 Cost:  0.32670346 
prediction:
 [151.66504 184.58601 181.04272 195.53494 142.21536] 

2000 Cost:  0.32666883 
prediction:
 [151.665   184.58603 181.04271 195.53506 142.21526] 



In [6]:
#with Matrix

x_data = [[73.,80.,75.,],
          [93.,88.,93.,],
          [89.,91.,90.,],
          [96.,98.,100.,],
          [73.,66.,70.,]]

y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

#필요할때 마다 추가가 가능하도록 None 설정 
X = tf.placeholder("float32",shape=[None,3]) 
Y = tf.placeholder("float32",shape=[None,1])
W = tf.Variable(tf.random_normal([3,1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X,W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                  feed_dict = {X:x_data, Y:y_data})
    if step % 10 == 0:
        print(step, "Cost: ",cost_val,"\nprediction:\n",hy_val,"\n")

0 Cost:  5349.752 
prediction:
 [[ 91.76569 ]
 [103.14121 ]
 [105.32887 ]
 [114.99363 ]
 [ 76.563644]] 

10 Cost:  16.732376 
prediction:
 [[156.35143]
 [180.79752]
 [181.82988]
 [198.30263]
 [135.80197]] 

20 Cost:  16.597311 
prediction:
 [[156.53157]
 [181.043  ]
 [182.0567 ]
 [198.55098]
 [135.99533]] 

30 Cost:  16.511494 
prediction:
 [[156.51686]
 [181.05423]
 [182.05276]
 [198.548  ]
 [136.01   ]] 

40 Cost:  16.426178 
prediction:
 [[156.50162]
 [181.06473]
 [182.04814]
 [198.5443 ]
 [136.02408]] 

50 Cost:  16.341293 
prediction:
 [[156.4864 ]
 [181.07518]
 [182.04352]
 [198.54059]
 [136.03813]] 

60 Cost:  16.256824 
prediction:
 [[156.47122]
 [181.08563]
 [182.03893]
 [198.53688]
 [136.05214]] 

70 Cost:  16.172894 
prediction:
 [[156.45612]
 [181.09604]
 [182.03435]
 [198.53319]
 [136.06612]] 

80 Cost:  16.089342 
prediction:
 [[156.44102]
 [181.10643]
 [182.02977]
 [198.52953]
 [136.08006]] 

90 Cost:  16.006311 
prediction:
 [[156.42598]
 [181.11678]
 [182.0252 ]
 [198.

980 Cost:  10.152323 
prediction:
 [[155.23936]
 [181.93355]
 [181.6658 ]
 [198.23317]
 [137.19344]] 

990 Cost:  10.101218 
prediction:
 [[155.2276 ]
 [181.94165]
 [181.66225]
 [198.23024]
 [137.20436]] 

1000 Cost:  10.050387 
prediction:
 [[155.21588]
 [181.94972]
 [181.6587 ]
 [198.22731]
 [137.21527]] 

1010 Cost:  9.999823 
prediction:
 [[155.2042 ]
 [181.95778]
 [181.65517]
 [198.2244 ]
 [137.22615]] 

1020 Cost:  9.949583 
prediction:
 [[155.19252]
 [181.96579]
 [181.65164]
 [198.22147]
 [137.23697]] 

1030 Cost:  9.899534 
prediction:
 [[155.1809 ]
 [181.9738 ]
 [181.64812]
 [198.21857]
 [137.2478 ]] 

1040 Cost:  9.849804 
prediction:
 [[155.16931]
 [181.9818 ]
 [181.64462]
 [198.21567]
 [137.25859]] 

1050 Cost:  9.800311 
prediction:
 [[155.15775]
 [181.98976]
 [181.64111]
 [198.21277]
 [137.26935]] 

1060 Cost:  9.751162 
prediction:
 [[155.14621]
 [181.9977 ]
 [181.63763]
 [198.2099 ]
 [137.28006]] 

1070 Cost:  9.702187 
prediction:
 [[155.1347 ]
 [182.00562]
 [181.63416

1920 Cost:  6.373434 
prediction:
 [[154.26414]
 [182.60551]
 [181.37132]
 [197.98643]
 [138.10374]] 

1930 Cost:  6.3426194 
prediction:
 [[154.25505]
 [182.61177]
 [181.36856]
 [197.98409]
 [138.11224]] 

1940 Cost:  6.3119774 
prediction:
 [[154.246  ]
 [182.61803]
 [181.36584]
 [197.98177]
 [138.12074]] 

1950 Cost:  6.2814894 
prediction:
 [[154.23698]
 [182.62425]
 [181.36311]
 [197.97945]
 [138.12923]] 

1960 Cost:  6.251188 
prediction:
 [[154.22797]
 [182.63045]
 [181.36041]
 [197.97711]
 [138.13766]] 

1970 Cost:  6.221048 
prediction:
 [[154.219  ]
 [182.63664]
 [181.3577 ]
 [197.97481]
 [138.14609]] 

1980 Cost:  6.1910567 
prediction:
 [[154.21004]
 [182.64282]
 [181.35501]
 [197.9725 ]
 [138.1545 ]] 

1990 Cost:  6.1612525 
prediction:
 [[154.20111]
 [182.64897]
 [181.35231]
 [197.97021]
 [138.16287]] 

2000 Cost:  6.1315856 
prediction:
 [[154.19218]
 [182.6551 ]
 [181.34962]
 [197.96791]
 [138.17122]] 

