# Lecture 8
## Tensor Manipulation
<hr/>

In [1]:
import tensorflow as tf

/Users/che/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [4]:
t = tf.constant([1,2,3,4])
s = tf.Session()
tf.shape(t).eval(session = s)

array([4], dtype=int32)

In [16]:
matrix1 = tf.constant([[1,2],[3,4]])
matrix2 = tf.constant([[1],[2]])
print(matrix1.shape)
print(matrix2.shape)
print('\n',tf.matmul(matrix1, matrix2).eval(session=s),'\n')
print((matrix1 * matrix2).eval(session=s))

(2, 2)
(2, 1)

 [[ 5]
 [11]] 

[[1 2]
 [6 8]]


axis

reshape

tf.squeeze()

tf.expand_dims

tf.stack


tf.ones_like

tf.zeros_like