# Lecture 6
## Softmax Regression
<hr/>
```python
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis = 1))
```

In [1]:
import numpy as np
import tensorflow as tf

x_data = [[1,2,1,1], [2,1,3,2], [3,1,3,4], [4,1,5,5], [1,7,5,5], [1,2,5,6], [1,6,6,6], [1,7,7,7]]
y_data = [[0,0,1], [0,0,1], [0,0,1], [0,1,0], [0,1,0], [0,1,0], [1,0,0], [1,0,0]]

X = tf.placeholder(tf.float32, [None, 4])
Y = tf.placeholder(tf.float32, [None, 3])
nb_classes = 3

W = tf.Variable(tf.random_normal([4,nb_classes]), name = 'weight')
b = tf.Variable(tf.random_normal([nb_classes]), name = 'bias')

hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis = 1))

train = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    for step in range(2001):
        sess.run(train, feed_dict={X: x_data, Y: y_data})
        if step % 200 == 0:
            print('\nstep:',step, 'cost:', sess.run(cost, feed_dict={X: x_data, Y: y_data}))
            print('hypothesis:\n',sess.run(hypothesis, feed_dict={X: x_data, Y: y_data}))
            print('Y_:\n',np.round(sess.run(hypothesis, feed_dict={X: x_data, Y: y_data})))
    
    a = sess.run(hypothesis, feed_dict={X:x_data})
    print('\n\n\n')
    print(a, '\n' ,sess.run(tf.arg_max(a,1)))
    print(np.round(a))

/Users/che/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters



step: 0 cost: 2.5770864
hypothesis:
 [[8.28293204e-01 6.91876486e-02 1.02519125e-01]
 [8.98481250e-01 9.50129479e-02 6.50581159e-03]
 [8.15737247e-01 1.83442906e-01 8.19908222e-04]
 [8.71359646e-01 1.28543422e-01 9.69623798e-05]
 [5.48683941e-01 9.71869901e-02 3.54129046e-01]
 [6.76619411e-02 9.30836558e-01 1.50148105e-03]
 [4.60728526e-01 4.32293057e-01 1.06978364e-01]
 [3.79696757e-01 5.06713748e-01 1.13589443e-01]]
Y_:
 [[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]
 [0. 1. 0.]]

step: 200 cost: 0.6416929
hypothesis:
 [[0.0433987  0.06240738 0.8941939 ]
 [0.05480285 0.15786603 0.7873311 ]
 [0.00869868 0.30937776 0.6819235 ]
 [0.00841438 0.4052195  0.5863661 ]
 [0.87976754 0.07014361 0.05008895]
 [0.4951051  0.5002055  0.00468939]
 [0.90830845 0.08482619 0.0068654 ]
 [0.9509232  0.04752599 0.00155084]]
Y_:
 [[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]

step: 400 cost: 0.5297736
hypothesis:
 [[6.

## softmax cross entropy with logits
<hr/>
```python
logits = tf.matmul(X,W) + b
hypothesis = tf.nn.softmax(logits)

# Cross entropy cost/loss
cost = tf.reduce.mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis = 1))

# Cross entropy cost/loss
cost_i = tf.nn.softmax_cross_entropy_with_logits(logits = logits, labels = Y_one_hot)
cost = tf.reduce_mean(cost_i)
```

  ### Animal classification 
    with sotfmax_cross_entropy_with_logits

<hr/>

In [2]:
xy = np.loadtxt('data-04-zoo.csv', delimiter=',', dtype=np.float32)
x_data = xy[:,:-1]
y_data = xy[:,[-1]]

In [3]:
X = tf.placeholder(tf.float32, shape=[None,16])
Y = tf.placeholder(tf.int32, shape=[None,1])
nb_classes = 7

Y_one_hot = tf.one_hot(Y, nb_classes)
Y_one_hot = tf.reshape(Y_one_hot, [-1, nb_classes])

W = tf.Variable(tf.random_normal([16,nb_classes]), name = 'weight')
b = tf.Variable(tf.random_normal([nb_classes]), name = 'bias')

logits = tf.matmul(X, W) + b
hypothesis = tf.nn.softmax(logits)

cost_i = tf.nn.softmax_cross_entropy_with_logits(logits = logits, labels = Y_one_hot)
cost = tf.reduce_mean(cost_i)

train = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

#prediction 
prediction = tf.argmax(hypothesis, 1)
correct_prediction = tf.equal(prediction, tf.arg_max(Y_one_hot, 1))
#accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
accuracy = tf.reduce_mean(tf.to_float(correct_prediction))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(2001):
        sess.run(train, feed_dict = {X: x_data, Y: y_data})
        
        if step % 100 == 0:
            loss, acc = sess.run([cost, accuracy], feed_dict = {X: x_data, Y: y_data})
            print('step: {:5}\tLoss: {:.3f}\tAcc: {:.2%}'.format(step,loss,acc))
            #print('step:', step, 'cost:', sess.run(cost, feed_dict = {X: x_data, Y: y_data}))
            #print(sess.run(tf.arg_max(tf.nn.softmax(logits), 1), feed_dict = {X: x_data, Y: y_data}))
            
            

    
    pred = sess.run(prediction, feed_dict={X: x_data})
    for p, y in zip(pred, y_data.flatten()):
        print("[{}] Prediction: {} True Y: {}".format(p == int(y), p, int(y)))

Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See @{tf.nn.softmax_cross_entropy_with_logits_v2}.

step:     0	Loss: 4.918	Acc: 15.84%
step:   100	Loss: 0.572	Acc: 85.15%
step:   200	Loss: 0.375	Acc: 91.09%
step:   300	Loss: 0.290	Acc: 91.09%
step:   400	Loss: 0.236	Acc: 92.08%
step:   500	Loss: 0.197	Acc: 94.06%
step:   600	Loss: 0.168	Acc: 95.05%
step:   700	Loss: 0.146	Acc: 96.04%
step:   800	Loss: 0.129	Acc: 96.04%
step:   900	Loss: 0.115	Acc: 99.01%
step:  1000	Loss: 0.103	Acc: 100.00%
step:  1100	Loss: 0.094	Acc: 100.00%
step:  1200	Loss: 0.086	Acc: 100.00%
step:  1300	Loss: 0.079	Acc: 100.00%
step:  1400	Loss: 0.074	Acc: 100.00%
step:  1500	Loss: 0.069	Acc: 100.00%
step:  1600	Loss: 0.064	Acc: 100.00%
step:  1700	Loss: 0.061	Acc: 100.00%
step:  1800	Loss: 0.057	Acc: 100.00%
step:  1900	Loss: 0.054	Acc: 100.00%
step:  2000	Loss: 0.052	Acc: 100.00%
[True] Prediction: 0 True Y: 0
[True] Pre

In [4]:
# Why we had to use tf.reshape to y_one_hot
yy = tf.one_hot(Y, nb_classes)
s = tf.Session()
s.run(tf.global_variables_initializer())
d = s.run(yy, feed_dict={Y: y_data})
print(d.shape,' >> ',d.reshape([-1,7]).shape)
print(d.shape,' >> ',d.reshape([101,-1]).shape)
print(d.shape,' >> ',d.reshape([101,7]).shape)

(101, 1, 7)  >>  (101, 7)
(101, 1, 7)  >>  (101, 7)
(101, 1, 7)  >>  (101, 7)


array([-0.36276585, -0.74894863, -0.17169347, -1.0916923 ,  0.04430841,
        2.0111554 , -0.13605173], dtype=float32)