# Lectrue 5
## Logistic(Regression) Classification
<hr/>

### Classification ?
- #### Spam Detection: Spam or Ham
- #### Facebook feed: Show or Hide
- #### Credit card fraudulent transaction: legitimate/fraud

### Encoding with 0 , 1 
- #### Spam Detection: Spam(1) or Ham(0)
- #### Facebook feed: Show(1) or Hide(0)
- #### Credit card fraudulent transaction: legitimate(0)/fraud(1)

### Problem with Linear regression 
- #### We know Y is 0 or 1 
- #### Hypothesis can give values large than 1 or lees than 0 
<hr/>

### Logistic Hypothesis
- #### \\(g(z) = \dfrac{1}{1+e^{-z}}\\)
- #### \\(H(X) = \dfrac{1}{1+e{-W^TX}}\\)

### New cost function for logistic
- #### \\( cost(W) = \frac{1}{m}\sum\\)    
- #### \\(   c(H(x),y)\\)
- #### \\(c(H(x),y) = {-log(H(x)) : y = 1} ,{-log(1-H(x)) : y = 0}\\)
- #### with out if condition
 
 - #### \\(c(H(x),y) = -ylog(H(x))-(1-y)log(1-H(x))\\)

### Minimize cost - Grandient decent algorithm
- #### \\(cost(W) = -\frac{1}{m}\sum{ylog}(H(x))+(1-y)log(1-H(x))\\)
- #### \\(W:= W- \alpha\dfrac{\alpha}{\alpha{W}}cost(W)\\)

```python
# cost function 
cost = -tf.reduce_mean((Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis)))
# minimize
a = tf.Variable(0.1) #Learning rate, alpha
optimizer = tf.train.GrandientDescentOptimizer(a)
train = optimizer.minimize(cost)
```

<hr/>
## example

In [5]:
import tensorflow as tf

x_data = [ [1, 2], [2, 3], [3, 1], [4, 3], [5, 3], [6, 2] ]
y_data = [ [0], [0], [0], [1], [1], [1] ] # 0 is fail , 1 is pass  

X = tf.placeholder(tf.float32, shape = [None, 2])
Y = tf.placeholder(tf.float32, shape = [None, 1])
W = tf.Variable(tf.random_normal([2, 1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias' )

hypothesis = tf.sigmoid(tf.matmul(X, W) + b)
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) 
                                      * tf.log(1 - hypothesis))

train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)

# Accuracy computation
# True if hypothesis > 0.5 else False 
# tf.cast makes it to 0 or 1 
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))


with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(10001):
        cost_val, _ = sess.run([cost, train], feed_dict={X: x_data, Y: y_data})
        if step % 200 == 0:
            print(step, cost_val)
    
    h, c, a = sess.run([hypothesis, predicted, accuracy],
                      feed_dict={X: x_data, Y: y_data})
    print("\nHypothesis:\n",h,"\nCorrect (Y):\n",c,"\nAccuracy:\n",a)

/Users/che/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


0 1.873773
200 0.69970316
400 0.56934863
600 0.50987494
800 0.47580078
1000 0.4520335
1200 0.43310118
1400 0.4167769
1600 0.4020622
1800 0.38847208
2000 0.37575328
2200 0.36376306
2400 0.35241374
2600 0.34164616
2800 0.33141634
3000 0.3216886
3200 0.3124323
3400 0.3036199
3600 0.29522577
3800 0.2872264
4000 0.27959943
4200 0.2723237
4400 0.2653794
4600 0.25874776
4800 0.25241107
5000 0.24635263
5200 0.240557
5400 0.2350093
5600 0.22969566
5800 0.22460319
6000 0.21971966
6200 0.21503371
6400 0.21053457
6600 0.20621222
6800 0.20205724
7000 0.19806081
7200 0.1942147
7400 0.19051106
7600 0.18694262
7800 0.18350257
8000 0.18018447
8200 0.17698228
8400 0.1738903
8600 0.17090327
8800 0.16801615
9000 0.16522422
9200 0.16252308
9400 0.15990843
9600 0.15737636
9800 0.1549232
10000 0.15254544

Hypothesis:
 [[0.03203372]
 [0.1605638 ]
 [0.31099632]
 [0.77859575]
 [0.93780524]
 [0.9795767 ]] 
Correct (Y):
 [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 
Accuracy:
 1.0


<hr/>
## example with data file
### Classifying diabetes

In [9]:
import numpy as np 

xy = np.loadtxt('data-03-diabetes.csv', delimiter = ',', dtype = np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

X = tf.placeholder(tf.float32, shape=[None, 8])
Y = tf.placeholder(tf.float32, shape=[None, 1])
W = tf.Variable(tf.random_normal([8, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = tf.sigmoid(tf.matmul(X, W) + b)
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))
train = tf.train.GradientDescentOptimizer(learning_rate=1e-2).minimize(cost)

predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    feed = {X: x_data, Y: y_data}
    for step in range(10001):
        sess.run(train, feed_dict=feed)
        if step % 200 == 0:
            print(step, sess.run(cost, feed_dict=feed))
            
    h, c, a = sess.run([hypothesis, predicted, accuracy], feed_dict=feed)
    print('\nHypothesis:\n', h, '\nCorrect:\n', c, '\nAccuracy:\n', a * 100,'%')
    

0 0.7850017
200 0.6893259
400 0.65356886
600 0.634434
800 0.61991155
1000 0.6074248
1200 0.59636015
1400 0.58647794
1600 0.5776216
1800 0.5696636
2000 0.5624955
2200 0.55602366
2400 0.55016637
2600 0.5448532
2800 0.5400227
3000 0.5356212
3200 0.53160214
3400 0.52792454
3600 0.52455246
3800 0.5214547
4000 0.5186032
4200 0.515974
4400 0.513545
4600 0.51129746
4800 0.50921416
5000 0.5072801
5200 0.50548184
5400 0.50380737
5600 0.5022459
5800 0.50078773
6000 0.49942434
6200 0.49814788
6400 0.49695116
6600 0.4958281
6800 0.49477285
7000 0.49378026
7200 0.49284545
7400 0.4919643
7600 0.4911329
7800 0.49034756
8000 0.4896051
8200 0.48890254
8400 0.48823714
8600 0.48760644
8800 0.48700806
9000 0.48643994
9200 0.48590007
9400 0.48538688
9600 0.4848984
9800 0.48443335
10000 0.48399013

Hypothesis:
 [[0.40197876]
 [0.92255795]
 [0.2710747 ]
 [0.9404566 ]
 [0.31289032]
 [0.7940869 ]
 [0.9466991 ]
 [0.6071723 ]
 [0.22645019]
 [0.5553395 ]
 [0.7144361 ]
 [0.17914253]
 [0.41180548]
 [0.18036759]
 [0.

 [[0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1